"""Block-state registry for protocol 775 (Minecraft 26.1.2).

No `minecraft-data`-equivalent package exists for a brand-new version --
this isn't written down anywhere as a static table in the game's source
either: block state ids are assigned at runtime by iterating
`BuiltInRegistries.BLOCK` and, for each block, iterating
`block.getStateDefinition().getPossibleStates()`
(`net.minecraft.world.level.block.Blocks`'s static initializer, confirmed by
reading the decompiled source). Real collision-shape solidity for irregular
blocks (stairs, slabs, fences, ...) is computed from actual `VoxelShape`
geometry per block-class override, not a static flag -- also not something
safe to reimplement from source text.

So this table was generated by running a throwaway Fabric dev server
(pinned to 26.1.2 via mods/VillagerHelper, the same project used earlier to
get decompiled sources/packet ids) with a temporary mod hook that dumped
every block state's real id and properties to JSON right after registries
finished loading, then immediately halted the server. See git history for
the generator; it isn't kept in-tree since it's a one-shot extraction, not
something we run repeatedly.

Per-entry fields (mirroring what mineflayer-pathfinder's movements.js reads
off Node's minecraft-data for its cost model):
  id: global block-state id, exactly as it appears in a chunk's paletted
      block container and any other packet using the "global" block-state
      palette (e.g. ClientboundBlockUpdatePacket, not yet parsed).
  name: namespaced block id (e.g. "minecraft:stone"). Multiple states share
      a name (different property combinations -- e.g. stair
      facing/half/shape/waterlogged).
  air: state.isAir().
  solid: state.isCollisionShapeFullBlock(...) -- a full 1x1x1 collision
      cube, i.e. "you can stand on this and can't walk through it." False
      for slabs/stairs/fences/etc even though they do have partial
      collision (see hasCollision).
  has_collision: state.getCollisionShape(...) is non-empty -- i.e. *some*
      part of the voxel blocks movement, even if not a full cube.
  liquid: !state.getFluidState().isEmpty().
  ladder: the owning block is in the `minecraft:climbable` block tag
      (ladders, vines, scaffolding).
  shapes: state.getCollisionShape(...).toAabbs() -- the real collision
      geometry as a list of axis-aligned boxes, each
      (min_x, min_y, min_z, max_x, max_y, max_z) in block-local coordinates
      (0.0-1.0 per axis for a shape that stays within the block; some
      shapes, e.g. certain fence/wall connections, can extend slightly
      outside that range). Empty list for air or any other
      no-collision block. This is what makes real physics simulation
      (minebot/physics/) collide correctly against slabs/stairs/fences
      instead of treating every solid block as a full cube.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path

_TABLE_PATH = Path(__file__).resolve().parent / "block_registry_775.json"


Box = tuple[float, float, float, float, float, float]


@dataclass(frozen=True)
class BlockStateInfo:
    id: int
    name: str
    air: bool
    solid: bool
    has_collision: bool
    liquid: bool
    ladder: bool
    shapes: tuple[Box, ...]


@dataclass(frozen=True)
class BlockRegistry:
    _by_id: dict[int, BlockStateInfo]

    def get(self, state_id: int) -> BlockStateInfo | None:
        return self._by_id.get(state_id)

    def is_air(self, state_id: int) -> bool:
        info = self._by_id.get(state_id)
        return info is None or info.air

    def is_solid(self, state_id: int) -> bool:
        info = self._by_id.get(state_id)
        return info is not None and info.solid

    def is_liquid(self, state_id: int) -> bool:
        info = self._by_id.get(state_id)
        return info is not None and info.liquid

    def is_ladder(self, state_id: int) -> bool:
        info = self._by_id.get(state_id)
        return info is not None and info.ladder

    def states_named(self, name: str) -> list[BlockStateInfo]:
        return [info for info in self._by_id.values() if info.name == name]


def load_block_registry(path: Path = _TABLE_PATH) -> BlockRegistry:
    with path.open() as f:
        raw = json.load(f)

    by_id = {
        entry["id"]: BlockStateInfo(
            id=entry["id"],
            name=entry["name"],
            air=entry["air"],
            solid=entry["solid"],
            has_collision=entry["hasCollision"],
            liquid=entry["liquid"],
            ladder=entry["ladder"],
            shapes=tuple(tuple(box) for box in entry["shapes"]),
        )
        for entry in raw["entries"]
    }
    return BlockRegistry(_by_id=by_id)


BLOCK_REGISTRY = load_block_registry()
