"""Packet ID <-> name lookup for protocol 775 (Minecraft 26.1.2).

Backed by packets_775.json, generated by tools/extract_packet_ids.py from the
decompiled vanilla source. See that script's docstring for how packet IDs are
derived (declaration order within each state's registration builder).
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Literal

Direction = Literal["serverbound", "clientbound"]

_TABLE_PATH = Path(__file__).resolve().parent / "packets_775.json"


@dataclass(frozen=True)
class PacketRegistry:
    protocol_version: int
    minecraft_version: str
    # state -> direction -> {id: name}
    _states: dict[str, dict[str, dict[int, str]]]
    # state -> direction -> {name: id}, derived for encode-side lookups
    _reverse: dict[str, dict[str, dict[str, int]]]

    def name_for(self, state: str, direction: Direction, packet_id: int) -> str | None:
        return self._states.get(state, {}).get(direction, {}).get(packet_id)

    def id_for(self, state: str, direction: Direction, name: str) -> int:
        try:
            return self._reverse[state][direction][name]
        except KeyError as exc:
            raise KeyError(
                f"no packet named {name!r} registered for state={state!r} direction={direction!r}"
            ) from exc

    def packet_names(self, state: str, direction: Direction) -> list[str]:
        return list(self._reverse.get(state, {}).get(direction, {}).keys())


def load_registry(path: Path = _TABLE_PATH) -> PacketRegistry:
    with path.open() as f:
        raw = json.load(f)

    states: dict[str, dict[str, dict[int, str]]] = {}
    reverse: dict[str, dict[str, dict[str, int]]] = {}

    for state, directions in raw["states"].items():
        states[state] = {}
        reverse[state] = {}
        for direction, id_to_name in directions.items():
            id_map = {int(k): v for k, v in id_to_name.items()}
            states[state][direction] = id_map
            reverse[state][direction] = {v: k for k, v in id_map.items()}

    return PacketRegistry(
        protocol_version=raw["protocol_version"],
        minecraft_version=raw["minecraft_version"],
        _states=states,
        _reverse=reverse,
    )


REGISTRY = load_registry()
