"""Extract Minecraft packet ID tables for 26.1.2 (protocol 775) from the
decompiled vanilla server/client sources produced by Fabric Loom's
`genSources` task.

Packet IDs are not written down anywhere explicitly in modern (1.20.5+)
Minecraft source: each protocol phase registers its packets via a fluent
`ProtocolInfoBuilder.addPacket(TYPE, CODEC)` chain, and a packet's numeric ID
is simply its zero-based position in that chain (see
`ProtocolInfoBuilder.buildDetails`, which does
`for (i, entry) in enumerate(codecs): output.accept(entry.type, i)`).

This script parses the five `*Protocols.java` registration files directly out
of the Loom-generated sources jar and reconstructs the id -> packet name
table for every (state, direction) pair, writing the result to
minebot/protocol/packets_775.json.

Source of truth: mods/VillagerHelper/.gradle/loom-cache/minecraftMaven/net/minecraft/
    minecraft-merged-043a8b3edf/26.1.2/minecraft-merged-043a8b3edf-26.1.2-sources.jar
(generated by running `./gradlew genSources` in mods/VillagerHelper, which
already targets minecraft_version=26.1.2).
"""

from __future__ import annotations

import argparse
import json
import re
import zipfile
from pathlib import Path

# One entry per registration file: (path inside the sources jar, state name,
# variable name of the builder chain that registers SERVERBOUND packets,
# variable name of the one that registers CLIENTBOUND packets).
# A state with only one direction has None for the other.
PROTOCOL_FILES = [
    (
        "net/minecraft/network/protocol/handshake/HandshakeProtocols.java",
        "handshake",
        "SERVERBOUND_TEMPLATE",
        None,
    ),
    (
        "net/minecraft/network/protocol/status/StatusProtocols.java",
        "status",
        "SERVERBOUND_TEMPLATE",
        "CLIENTBOUND_TEMPLATE",
    ),
    (
        "net/minecraft/network/protocol/login/LoginProtocols.java",
        "login",
        "SERVERBOUND_TEMPLATE",
        "CLIENTBOUND_TEMPLATE",
    ),
    (
        "net/minecraft/network/protocol/configuration/ConfigurationProtocols.java",
        "configuration",
        "SERVERBOUND_TEMPLATE",
        "CLIENTBOUND_TEMPLATE",
    ),
    (
        "net/minecraft/network/protocol/game/GameProtocols.java",
        "play",
        "SERVERBOUND_TEMPLATE",
        "CLIENTBOUND_TEMPLATE",
    ),
]

# Matches `builder -> builder.addPacket(TYPE, ...)` style chains: captures the
# assignment target, then everything up to the closing `);` of the call.
ASSIGNMENT_RE = re.compile(
    r"(?P<var>[A-Z_]+)\s*=\s*ProtocolInfoBuilder\.\w+\(\s*"
    r"ConnectionProtocol\.\w+,\s*"
    r"builder\s*->\s*(?P<chain>.*?)\n\s*\);",
    re.DOTALL,
)

# Matches one `.addPacket(SomeTypes.SOME_NAME, ...)` or
# `.withBundlePacket(SomeTypes.SOME_NAME, ...)` link in the chain. The bundle
# delimiter packet registered by withBundlePacket occupies its own ID slot,
# same as a normal addPacket, so both call forms count.
ADD_PACKET_RE = re.compile(
    r"\.(?:addPacket|withBundlePacket)\(\s*(?:[A-Za-z0-9_]+\.)?([A-Z][A-Z0-9_]*)\s*,"
)


def extract_chain_packet_names(chain_src: str) -> list[str]:
    names = []
    for match in ADD_PACKET_RE.finditer(chain_src):
        names.append(match.group(1))
    return names


def parse_protocols_file(source: str) -> dict[str, list[str]]:
    """Returns {builder_var_name: [packet_name, ...]} in declaration order."""
    result: dict[str, list[str]] = {}
    for match in ASSIGNMENT_RE.finditer(source):
        var = match.group("var")
        chain = match.group("chain")
        result[var] = extract_chain_packet_names(chain)
    return result


def build_table(sources_jar: Path) -> dict:
    table: dict[str, dict] = {}
    with zipfile.ZipFile(sources_jar) as zf:
        for rel_path, state, sb_var, cb_var in PROTOCOL_FILES:
            src = zf.read(rel_path).decode("utf-8")
            chains = parse_protocols_file(src)

            state_entry: dict[str, dict[str, str]] = {}

            if sb_var is not None:
                names = chains.get(sb_var)
                if not names:
                    raise RuntimeError(f"no {sb_var} chain found in {rel_path}")
                state_entry["serverbound"] = {str(i): n for i, n in enumerate(names)}

            if cb_var is not None:
                names = chains.get(cb_var)
                if not names:
                    raise RuntimeError(f"no {cb_var} chain found in {rel_path}")
                state_entry["clientbound"] = {str(i): n for i, n in enumerate(names)}

            table[state] = state_entry
    return table


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--sources-jar",
        type=Path,
        default=Path(
            "/home/colaila/git/mods/VillagerHelper/.gradle/loom-cache/minecraftMaven/"
            "net/minecraft/minecraft-merged-043a8b3edf/26.1.2/"
            "minecraft-merged-043a8b3edf-26.1.2-sources.jar"
        ),
        help="Path to the Loom-generated decompiled sources jar for 26.1.2",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=Path(__file__).resolve().parent.parent / "minebot" / "protocol" / "packets_775.json",
    )
    args = parser.parse_args()

    if not args.sources_jar.exists():
        raise SystemExit(
            f"sources jar not found at {args.sources_jar}\n"
            "Run `./gradlew genSources` in mods/VillagerHelper first."
        )

    table = build_table(args.sources_jar)

    args.out.parent.mkdir(parents=True, exist_ok=True)
    with args.out.open("w") as f:
        json.dump(
            {
                "protocol_version": 775,
                "minecraft_version": "26.1.2",
                "source": "genSources decompile of mods/VillagerHelper 26.1.2 build",
                "states": table,
            },
            f,
            indent=2,
        )

    total_packets = sum(
        len(direction_map)
        for state in table.values()
        for direction_map in state.values()
    )
    print(f"Wrote {args.out} ({total_packets} packet ids across {len(table)} states)")


if __name__ == "__main__":
    main()
